services:
  - type: web
    name: fastapi-bot                   # Name of your Render service
    runtime: python
    plan: free                          # Free tier: 512 MB RAM, spins down after 15 min inactivity
    rootDir: src/fast_api                # Folder containing main.py
    buildCommand: "pip install -r ../requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: EMAIL
        value: "24f3004305@ds.study.iitm.ac.in"  # Your Gmail ID
      - key: APP_PASSWORD
        value: "sfkh miwi nsjj meny"           # Your Gmail App Password
      - key: SESSION_PATH
        value: "./session"                     # Path to your WhatsApp session folder (inside fast_api)